"""Add job postings table

Revision ID: 107acb4b027c
Revises: 
Create Date: 2025-11-06 18:57:58.844601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '107acb4b027c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('salary', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('date_posted', sa.String(), nullable=True))
    op.add_column('job_postings', sa.Column('extracted_skills', sa.JSON(), nullable=True))
    op.add_column('job_postings', sa.Column('detailed_skills', sa.JSON(), nullable=True))
    op.add_column('job_postings', sa.Column('collected_at', sa.DateTime(), nullable=False))
    op.drop_column('job_postings', 'required_skills')
    op.drop_column('job_postings', 'salary_min')
    op.drop_column('job_postings', 'posted_date')
    op.drop_column('job_postings', 'salary_max')
    op.drop_column('job_postings', 'remote')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('remote', sa.BOOLEAN(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_max', sa.INTEGER(), nullable=True))
    op.add_column('job_postings', sa.Column('posted_date', sa.DATETIME(), nullable=True))
    op.add_column('job_postings', sa.Column('salary_min', sa.INTEGER(), nullable=True))
    op.add_column('job_postings', sa.Column('required_skills', sqlite.JSON(), nullable=True))
    op.drop_column('job_postings', 'collected_at')
    op.drop_column('job_postings', 'detailed_skills')
    op.drop_column('job_postings', 'extracted_skills')
    op.drop_column('job_postings', 'date_posted')
    op.drop_column('job_postings', 'salary')
    # ### end Alembic commands ###
